# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-20 03:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hoisting', '0003_image_private'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_vote', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hoisting.Image')),
            ],
        ),
    ]
