# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-20 04:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hoisting', '0004_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='image_vote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hoisting.Image'),
        ),
    ]
