# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-20 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoisting', '0005_auto_20180220_0403'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='ip',
            field=models.GenericIPAddressField(default='127.0.0.1'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set([('image_vote', 'ip')]),
        ),
    ]
