# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-11 04:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoisting', '0002_auto_20180211_0329'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
